language: node_js
node_js:
  - 8
# Install the newest version of yarn, otherwise the install will fail
# @see https://github.com/travis-ci/travis-ci/issues/7566
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn run dev &

script:
  - node --version
  - yarn --version
  - yarn run flow
  - yarn run cypress:run
notifications:
  email: false
cache:
  yarn: true
  directories:
    - node_modules