name: Dependabot auto-merge
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "${{github.event.pull_request.number}}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
