name: weekly episode deployment

on:
  schedule:
    - cron:  '30 12 * * 3'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-args: '--prod'
          now-org-id: ${{ secrets.ZEIT_ORG_ID }}
          now-project-id: ${{ secrets.ZEIT_PROJECT_ID}}
