name: send daily digest

on:
  schedule:
    - cron:  '13 * * * *'

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: 'https://brianlovin.com/api/hn/send?token=${{secrets.HN_TOKEN}}'