name: Lighthouse
on: [deployment_status]
jobs:
  audit:
    name: Performance Audit Preview Deployment
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Audit New Deployment
      uses: brianlovin/lighthouse-action@master
      with:
        url: ${{ github.event.deployment_status.target_url }}
      id: lighthouse-new
    - name: Upload report to Zeit
      run: |
        now -t ${{ secrets.ZEIT_TOKEN }} deploy ./report/https*.html | tee zeit.log
        TARGET_URL=`tail -n1 zeit.log`
        curl -X POST https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d "{
            \"state\": \"success\",
            \"target_url\": \"${TARGET_URL}\",
            \"description\": \"Audit complete\",
            \"context\": \"Lighthouse\"
          }"
    - name: Audit Production
      uses: brianlovin/lighthouse-action@master
      with:
        url: https://brianlovin.com
      id: lighthouse-production
    - name: Comment Scores on PR
      uses: peter-evans/commit-comment@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          #### Lighthouse score for this commit:

          |  | PR | Production |
          |--|--|--|
          | Performance    | ${{ steps.lighthouse-new.outputs.performance }} | ${{ steps.lighthouse-production.outputs.performance }} |
          | Accessibility  | ${{ steps.lighthouse-new.outputs.accessibility }} | ${{ steps.lighthouse-production.outputs.accessibility }} |
          | Best Practices | ${{ steps.lighthouse-new.outputs.practices }} | ${{ steps.lighthouse-production.outputs.practices }} |
          | SEO            | ${{ steps.lighthouse-new.outputs.seo }} | ${{ steps.lighthouse-production.outputs.seo }} |

          *Note: SEO score will always be lower because `*.now.sh` urls are not indexed*
