name: Lighthouse
on: [deployment_status]
jobs:
  audit:
    name: Performance Audit Preview Deployment
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Audit Deployment
      uses: brianlovin/lighthouse-action@master
      with:
        url: ${{ github.event.deployment_status.target_url }}
      id: lighthouse
    - name: Upload report to Zeit
      run: |
        now -t ${{ secrets.ZEIT_TOKEN }} deploy ./report/https*.html | tee zeit.log
        TARGET_URL=`tail -n1 zeit.log`
        curl -X POST https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d "{
            \"state\": \"success\",
            \"target_url\": \"${TARGET_URL}\",
            \"description\": \"Audit complete\",
            \"context\": \"Lighthouse\"
          }"
    - name: Comment Scores on PR
      uses: peter-evans/commit-comment@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          #### Lighthouse score for this commit:

          Performance: **${{ steps.lighthouse.outputs.performance }} / 100**
          Accessibility: **${{ steps.lighthouse.outputs.accessibility }} / 100**
          Best Practices: **${{ steps.lighthouse.outputs.practices }} / 100**
          SEO: **${{ steps.lighthouse.outputs.seo }} / 100**
          PWA: **${{ steps.lighthouse.outputs.pwa }} / 100**

          Note: SEO score will always be lower because `*.now.sh` urls are not indexed