name: Lighthouse
on: [deployment_status]
jobs:
  audit:
    name: Performance Audit Preview Deployment
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Audit Deployment
      uses: jakejarvis/lighthouse-action@master
      with:
        url: ${{ github.event.deployment_status.target_url }}

