name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress:
    runs-on: ubuntu-latest
    name: Integration
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          build: yarn run build
          start: yarn run start
          browser: chrome
