name: Integration
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  cypress:
    runs-on: ubuntu-latest
    name: Integration
    env:
      GHOST_API_KEY: ${{ secrets.GHOST_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Cypress
        uses: cypress-io/github-action@v1
        with:
          build: yarn run build
          start: yarn run start
          browser: chrome